#ifndef MIRAGE_FFI_H
#define MIRAGE_FFI_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status of the VPN connection.
 */
typedef enum MirageStatus {
    /**
     * Not connected
     */
    MIRAGE_STATUS_DISCONNECTED = 0,
    /**
     * Connection in progress
     */
    MIRAGE_STATUS_CONNECTING = 1,
    /**
     * Connected and tunneling traffic
     */
    MIRAGE_STATUS_CONNECTED = 2,
    /**
     * An error has occurred
     */
    MIRAGE_STATUS_ERROR = 3,
} MirageStatus;

/**
 * Opaque handle to a Mirage VPN client instance.
 * Created by `mirage_create()`, freed by `mirage_destroy()`.
 */
typedef struct MirageHandle MirageHandle;

/**
 * Error information returned from FFI calls.
 */
typedef struct MirageError {
    /**
     * Error code (0 = success)
     */
    int32_t code;
    /**
     * Human-readable error message (null-terminated)
     */
    char message[256];
} MirageError;

/**
 * Callback invoked by Rust to deliver outbound packets to the TUN interface.
 * Swift should call `packetFlow.writePackets()` with this data.
 *
 * - `data`: pointer to raw IP packet bytes
 * - `len`: length of the packet
 * - `context`: opaque pointer passed via `mirage_start()`
 */
typedef void (*MiragePacketWriteCallback)(const uint8_t *data, uintptr_t len, void *context);

/**
 * Callback invoked by Rust to report status changes.
 *
 * - `status`: new connection status
 * - `message`: optional human-readable message (null-terminated, may be null)
 * - `context`: opaque pointer passed via `mirage_start()`
 */
typedef void (*MirageStatusCallback)(enum MirageStatus status, const char *message, void *context);

/**
 * Tunnel configuration received from the server after authentication.
 * Swift uses this to construct `NEPacketTunnelNetworkSettings`.
 */
typedef struct MirageTunnelConfig {
    /**
     * Client VPN IPv4 address (e.g. "10.0.0.2/24"), null-terminated
     */
    char client_address[64];
    /**
     * Client VPN IPv6 address (optional, empty string if none)
     */
    char client_address_v6[64];
    /**
     * Server VPN IPv4 address (e.g. "10.0.0.1/24"), null-terminated
     */
    char server_address[64];
    /**
     * Server VPN IPv6 address (optional, empty string if none)
     */
    char server_address_v6[64];
    /**
     * MTU for the tunnel interface
     */
    uint16_t mtu;
    /**
     * DNS servers as JSON array string (e.g. '["1.1.1.1","8.8.8.8"]')
     */
    char dns_servers_json[512];
    /**
     * Routes as JSON array string (e.g. '["0.0.0.0/0","::0/0"]')
     */
    char routes_json[2048];
} MirageTunnelConfig;

/**
 * Callback invoked when tunnel configuration is available (after auth).
 * Swift should use this to call `setTunnelNetworkSettings()`.
 *
 * - `config`: tunnel configuration (addresses, DNS, routes, MTU)
 * - `context`: opaque pointer passed via `mirage_start()`
 */
typedef void (*MirageTunnelConfigCallback)(const struct MirageTunnelConfig *config, void *context);

/**
 * Connection metrics.
 */
typedef struct MirageMetrics {
    uint64_t bytes_sent;
    uint64_t bytes_received;
    uint64_t packets_sent;
    uint64_t packets_received;
    uint64_t uptime_seconds;
} MirageMetrics;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new Mirage VPN client from a TOML configuration string.
 *
 * Returns a heap-allocated `MirageHandle` on success, or `NULL` on failure.
 * The `err` parameter is populated with error details if the function fails.
 *
 * # Safety
 * - `config_toml` must be a valid null-terminated UTF-8 string.
 * - The returned handle must be freed with `mirage_destroy()`.
 */
struct MirageHandle *mirage_create(const char *config_toml, struct MirageError *err);

/**
 * Starts the VPN connection asynchronously.
 *
 * This function is non-blocking. Connection progress is reported via callbacks:
 * - `write_cb`: called when Rust has a packet to send to the TUN (→ Swift packetFlow)
 * - `status_cb`: called on status transitions (Connecting → Connected / Error)
 * - `tunnel_config_cb`: called after auth with tunnel parameters (addresses, DNS, routes)
 * - `context`: opaque pointer passed to all callbacks
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`.
 * - `context` must remain valid for the duration of the connection.
 * - Callbacks will be invoked from a Tokio worker thread.
 */
void mirage_start(struct MirageHandle *handle,
                  MiragePacketWriteCallback write_cb,
                  MirageStatusCallback status_cb,
                  MirageTunnelConfigCallback tunnel_config_cb,
                  void *context);

/**
 * Sends a packet from Swift into the Rust VPN tunnel.
 *
 * Call this from `packetFlow.readPackets()` to deliver inbound TUN packets to the tunnel.
 *
 * Returns `true` if the packet was accepted, `false` if the channel is full or disconnected.
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`.
 * - `data` must point to `len` bytes of valid memory.
 */
bool mirage_send_packet(struct MirageHandle *handle, const uint8_t *data, uintptr_t len);

/**
 * Stops the VPN connection gracefully.
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`.
 */
void mirage_stop(struct MirageHandle *handle);

/**
 * Frees all resources associated with the handle.
 *
 * After this call, the handle pointer is invalid and must not be used.
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`, or `NULL`.
 * - Must not be called while `mirage_start` callbacks are still running.
 */
void mirage_destroy(struct MirageHandle *handle);

/**
 * Returns the current connection status.
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`.
 */
enum MirageStatus mirage_get_status(const struct MirageHandle *handle);

/**
 * Returns a snapshot of current connection metrics.
 *
 * # Safety
 * - `handle` must be a valid pointer from `mirage_create()`.
 */
struct MirageMetrics mirage_get_metrics(const struct MirageHandle *handle);

/**
 * Frees a string that was returned by a `mirage_get_*` function.
 *
 * # Safety
 * - `s` must be a pointer returned by a `mirage_get_*` function, or `NULL`.
 */
void mirage_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MIRAGE_FFI_H */
